Add that `mn` requires bindeps
Without this installing errors with:

```rust
error: failed to parse manifest at `mnemos/tools/manganese/Cargo.toml`

Caused by:
  `artifact = …` requires `-Z bindeps` (cargo-binutils)
```